//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.10 at 07:53:45 PM CDT 
//


package com.att.gfp.data.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="passThru">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="enablePublish" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="eventNames">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="fileTargets">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fileTarget" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="enableLogging" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="eventNames">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="cascadeTargets">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cascadeTarget" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="enableCascading" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="scenarioName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="eventNames">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 *  
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ntdCorrelation",
    "pportProcessing",
    "adtranLinkDownCorrelation",
    "adtranAgingEvents",
    "vrfUpdate",
    "lportDomainClassification",
    "enrichLportAlarm",
    "adtranLPortCorrelation",
    "adtranCfmAlarm"
}) 
@XmlRootElement(name = "AdtranCorrelationPolicies")
public class AdtranCorrelationPolicies {
  
    @XmlElement(required = true)
    protected AdtranCorrelationPolicies.NtdCorrelation ntdCorrelation;
    @XmlElement(required = true)
    protected AdtranCorrelationPolicies.PportProcessing pportProcessing;
    @XmlElement(required = true)
    protected AdtranCorrelationPolicies.AdtranLinkDownCorrelation adtranLinkDownCorrelation;
	@XmlElement(required = true)
    protected AdtranCorrelationPolicies.AdtranAgingEvents adtranAgingEvents;
	@XmlElement(required = true) 
    protected AdtranCorrelationPolicies.VrfUpdate vrfUpdate;
	@XmlElement(required = true)  
    protected AdtranCorrelationPolicies.LportDomainClassification lportDomainClassification;
	@XmlElement(required = true)  
    protected AdtranCorrelationPolicies.EnrichLPortAlarm enrichLportAlarm;
	@XmlElement(required = true)  
    protected AdtranCorrelationPolicies.AdtranLPortCorrelation adtranLPortCorrelation;
	@XmlElement(required = true)  
    protected AdtranCorrelationPolicies.AdtranCfmAlarm adtranCfmAlarm;

    public AdtranCorrelationPolicies.AdtranCfmAlarm getAdtranCfmAlarm() {
		return adtranCfmAlarm;
	}   

	public void setAdtranCfmAlarm(
			AdtranCorrelationPolicies.AdtranCfmAlarm adtranCfmAlarm) {
		this.adtranCfmAlarm = adtranCfmAlarm;
	}

	public AdtranCorrelationPolicies.AdtranLPortCorrelation getAdtranLPortCorrelation() {
		return adtranLPortCorrelation;
	} 

	public void setAdtranLPortCorrelation(
			AdtranCorrelationPolicies.AdtranLPortCorrelation adtranLPortCorrelation) {
		this.adtranLPortCorrelation = adtranLPortCorrelation;
	}

	public AdtranCorrelationPolicies.EnrichLPortAlarm getEnrichLportAlarm() {
		return enrichLportAlarm;
	}
 
	public void setEnrichLportAlarm(
			AdtranCorrelationPolicies.EnrichLPortAlarm enrichLportAlarm) {
		this.enrichLportAlarm = enrichLportAlarm;
	}

	public AdtranCorrelationPolicies.LportDomainClassification getLportDomainClassification() {
		return lportDomainClassification;
	}
   
	public void setLportDomainClassification(
			AdtranCorrelationPolicies.LportDomainClassification lportDomainClassification) {
		this.lportDomainClassification = lportDomainClassification;
	}

	public AdtranCorrelationPolicies.VrfUpdate getVrfUpdate() {
		return vrfUpdate; 
	}

	public void setVrfUpdate(AdtranCorrelationPolicies.VrfUpdate vrfUpdate) {
		this.vrfUpdate = vrfUpdate;
	}

	/**
     * Gets the value of the passThru property.
     * 
     * @return
     *     possible object is
     *     {@link AdtranCorrelationPolicies.NtdCorrelation }
     *     
     */
    public AdtranCorrelationPolicies.NtdCorrelation getNtdCorrelation() {
        return ntdCorrelation;
    }

    /**
     * Sets the value of the passThru property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdtranCorrelationPolicies.NtdCorrelation }
     *     
     */
    public void setNtdCorrelation(AdtranCorrelationPolicies.NtdCorrelation value) {
        this.ntdCorrelation = value;
    }

    /**
     * Gets the value of the fileTargets property.
     * 
     * @return
     *     possible object is
     *     {@link AdtranCorrelationPolicies.PportProcessing }
     *     
     */
    public AdtranCorrelationPolicies.PportProcessing getPportProcessing() {
        return pportProcessing;
    }

    /**
     * Sets the value of the fileTargets property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdtranCorrelationPolicies.PportProcessing }
     *     
     */
    public void setPportProcessing(AdtranCorrelationPolicies.PportProcessing value) {
        this.pportProcessing = value;
    }
    
    public AdtranCorrelationPolicies.AdtranLinkDownCorrelation getAdtranLinkDownCorrelation() {
		return adtranLinkDownCorrelation;
	}

	public void setAdtranLinkDownCorrelation(
		AdtranCorrelationPolicies.AdtranLinkDownCorrelation adtranLinkDownCorrelation) {
		this.adtranLinkDownCorrelation = adtranLinkDownCorrelation;
	}
	
    /**
     * Gets the value of the cascadeTargets property.
     * 
     * @return
     *     possible object is
     *     {@link AdtranCorrelationPolicies.AdtranAgingEvents }
     *     
     */
    public AdtranCorrelationPolicies.AdtranAgingEvents getAdtranAgingEvents() {
        return adtranAgingEvents;
    }

    /**
     * Sets the value of the cascadeTargets property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdtranCorrelationPolicies.AdtranAgingEvents }
     *     
     */
    public void setAdtranAgingEvents(AdtranCorrelationPolicies.AdtranAgingEvents value) {
        this.adtranAgingEvents = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="cascadeTarget" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="enableCascading" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="scenarioName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="eventNames">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "agingInterval",
        "eventNames"
    })
    public static class AdtranAgingEvents {

        @XmlElement(required = true)
        protected String agingInterval;
		@XmlElement(required = true)
        protected AdtranCorrelationPolicies.AdtranAgingEvents.EventNames eventNames;
		
        public String getAgingInterval() {
			return agingInterval;
		}

		public void setAgingInterval(String agingInterval) {
			this.agingInterval = agingInterval;
		}

            /**
             * Gets the value of the eventNames property.
             * 
             * @return
             *     possible object is
             *     {@link AdtranCorrelationPolicies.AdtranAgingEvents.CascadeTarget.EventNames }
             *     
             */
            public AdtranCorrelationPolicies.AdtranAgingEvents.EventNames getEventNames() {
                return eventNames;
            }

            /**
             * Sets the value of the eventNames property.
             * 
             * @param value
             *     allowed object is
             *     {@link AdtranCorrelationPolicies.AdtranAgingEvents.CascadeTarget.EventNames }
             *     
             */
            public void setEventNames(AdtranCorrelationPolicies.AdtranAgingEvents.EventNames value) {
                this.eventNames = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "eventName"
            })
            public static class EventNames {

                protected List<String> eventName;

                /**
                 * Gets the value of the eventName property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the eventName property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getEventName().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getEventName() {
                    if (eventName == null) {
                        eventName = new ArrayList<String>();
                    }
                    return this.eventName;
                }

            }

        }



    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fileTarget" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="enableLogging" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="eventNames">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "eventsWithNoCorrelation",
        "eventsWithCorrelation"
    })
    public static class PportProcessing {

        protected AdtranCorrelationPolicies.PportProcessing.EventsWithNoCorrelation eventsWithNoCorrelation;
        protected AdtranCorrelationPolicies.PportProcessing.EventsWithCorrelation eventsWithCorrelation;
        /**
         * Gets the value of the eventNames property.
         * 
         * @return
         *     possible object is
         *     {@link AdtranCorrelationPolicies.AdtranAgingEvents.CascadeTarget.EventNames }
         *     
         */
        public AdtranCorrelationPolicies.PportProcessing.EventsWithNoCorrelation getEventsWithNoCorrelation() {
            return eventsWithNoCorrelation;
        }

        /**
         * Sets the value of the eventNames property.
         * 
         * @param value
         *     allowed object is
         *     {@link AdtranCorrelationPolicies.AdtranAgingEvents.CascadeTarget.EventNames }
         *     
         */
        public AdtranCorrelationPolicies.PportProcessing.EventsWithCorrelation getEventsWithCorrelation() {
            return eventsWithCorrelation;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "eventNames"
        })
        public static class EventsWithNoCorrelation {

            @XmlElement(required = true)
            protected AdtranCorrelationPolicies.PportProcessing.EventsWithNoCorrelation.EventNames eventNames;

            /**
             * Gets the value of the eventNames property.
             * 
             * @return
             *     possible object is
             *     {@link AdtranCorrelationPolicies.PportProcessing.FileTarget.EventNames }
             *     
             */
            public AdtranCorrelationPolicies.PportProcessing.EventsWithNoCorrelation.EventNames getEventNames() {
                return eventNames;
            }

            /**
             * Sets the value of the eventNames property.
             * 
             * @param value
             *     allowed object is
             *     {@link AdtranCorrelationPolicies.PportProcessing.FileTarget.EventNames }
             *     
             */
            public void setEventNames(AdtranCorrelationPolicies.PportProcessing.EventsWithNoCorrelation.EventNames value) {
                this.eventNames = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "eventName"
            })
            public static class EventNames {

                protected List<String> eventName;

                /**
                 * Gets the value of the eventName property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the eventName property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getEventName().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getEventName() {
                    if (eventName == null) {
                        eventName = new ArrayList<String>();
                    }
                    return this.eventName;
                }

            }

        }
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "eventNames"
        })
        public static class EventsWithCorrelation {

            @XmlElement(required = true)
            protected AdtranCorrelationPolicies.PportProcessing.EventsWithCorrelation.EventNames eventNames;

            /**
             * Gets the value of the eventNames property.
             * 
             * @return
             *     possible object is
             *     {@link AdtranCorrelationPolicies.PportProcessing.FileTarget.EventNames }
             *     
             */
            public AdtranCorrelationPolicies.PportProcessing.EventsWithCorrelation.EventNames getEventNames() {
                return eventNames;
            }

            /**
             * Sets the value of the eventNames property.
             * 
             * @param value
             *     allowed object is
             *     {@link AdtranCorrelationPolicies.PportProcessing.FileTarget.EventNames }
             *     
             */
            public void setEventNames(AdtranCorrelationPolicies.PportProcessing.EventsWithCorrelation.EventNames value) {
                this.eventNames = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "eventName"
            })
            public static class EventNames {

                protected List<String> eventName;

                /**
                 * Gets the value of the eventName property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the eventName property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getEventName().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getEventName() {
                    if (eventName == null) {
                        eventName = new ArrayList<String>();
                    }
                    return this.eventName;
                }

            }

        }

    }
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "adtLinkDownCorrKeys",
        "adtLinkDownAlarm"
    })
    public static class AdtranLinkDownCorrelation {

        protected AdtranCorrelationPolicies.AdtranLinkDownCorrelation.AdtLinkDownCorrKeys adtLinkDownCorrKeys;
        protected AdtranCorrelationPolicies.AdtranLinkDownCorrelation.AdtLinkDownAlarm adtLinkDownAlarm;
        /**
         * Gets the value of the eventNames property.
         * 
         * @return
         *     possible object is
         *     {@link AdtranCorrelationPolicies.AdtranAgingEvents.CascadeTarget.EventNames }
         *     
         */
        public AdtranCorrelationPolicies.AdtranLinkDownCorrelation.AdtLinkDownCorrKeys getAdtLinkDownCorrKeys() {
            return adtLinkDownCorrKeys;
        }

        /**
         * Sets the value of the eventNames property.
         * 
         * @param value
         *     allowed object is
         *     {@link AdtranCorrelationPolicies.AdtranAgingEvents.CascadeTarget.EventNames }
         *     
         */
        public AdtranCorrelationPolicies.AdtranLinkDownCorrelation.AdtLinkDownAlarm getAdtLinkDownAlarm() {
            return adtLinkDownAlarm;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "eventNames"
        })
        public static class AdtLinkDownCorrKeys {

            @XmlElement(required = true)
            protected AdtranCorrelationPolicies.AdtranLinkDownCorrelation.AdtLinkDownCorrKeys.EventNames eventNames;

            /**
             * Gets the value of the eventNames property.
             * 
             * @return
             *     possible object is
             *     {@link AdtranCorrelationPolicies.PportProcessing.FileTarget.EventNames }
             *     
             */
            public AdtranCorrelationPolicies.AdtranLinkDownCorrelation.AdtLinkDownCorrKeys.EventNames getEventNames() {
                return eventNames;
            }

            /**
             * Sets the value of the eventNames property.
             * 
             * @param value
             *     allowed object is
             *     {@link AdtranCorrelationPolicies.PportProcessing.FileTarget.EventNames }
             *     
             */
            public void setEventNames(AdtranCorrelationPolicies.AdtranLinkDownCorrelation.AdtLinkDownCorrKeys.EventNames value) {
                this.eventNames = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "eventName"
            })
            public static class EventNames {

                protected List<String> eventName;

                /**
                 * Gets the value of the eventName property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the eventName property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getEventName().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getEventName() {
                    if (eventName == null) {
                        eventName = new ArrayList<String>();
                    }
                    return this.eventName;
                }

            }

        }
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "eventNames"
        })
        public static class AdtLinkDownAlarm {

            @XmlElement(required = true)
            protected AdtranCorrelationPolicies.AdtranLinkDownCorrelation.AdtLinkDownAlarm.EventNames eventNames;

            /**
             * Gets the value of the eventNames property.
             * 
             * @return
             *     possible object is
             *     {@link AdtranCorrelationPolicies.PportProcessing.FileTarget.EventNames }
             *     
             */
            public AdtranCorrelationPolicies.AdtranLinkDownCorrelation.AdtLinkDownAlarm.EventNames getEventNames() {
                return eventNames;
            }

            /**
             * Sets the value of the eventNames property.
             * 
             * @param value
             *     allowed object is
             *     {@link AdtranCorrelationPolicies.PportProcessing.FileTarget.EventNames }
             *     
             */
            public void setEventNames(AdtranCorrelationPolicies.AdtranLinkDownCorrelation.AdtLinkDownAlarm.EventNames value) {
                this.eventNames = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "eventName"
            })
            public static class EventNames {

                protected List<String> eventName;

                /**
                 * Gets the value of the eventName property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the eventName property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getEventName().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getEventName() {  
                    if (eventName == null) {
                        eventName = new ArrayList<String>();
                    }
                    return this.eventName;
                }

            }

        }
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "adtLPortCorrKeys",
        "adtLPortPPPAlarm"
    })
    public static class AdtranLPortCorrelation {

        protected AdtranCorrelationPolicies.AdtranLPortCorrelation.AdtLPortCorrKeys adtLPortCorrKeys;
        protected AdtranCorrelationPolicies.AdtranLPortCorrelation.AdtLPortPPPAlarm adtLPortPPPAlarm;
        /**
         * Gets the value of the eventNames property.
         * 
         * @return
         *     possible object is
         *     {@link AdtranCorrelationPolicies.AdtranAgingEvents.CascadeTarget.EventNames }
         *     
         */
        public AdtranCorrelationPolicies.AdtranLPortCorrelation.AdtLPortCorrKeys getAdtLPortCorrKeys() {
            return adtLPortCorrKeys;
        }

        /**
         * Sets the value of the eventNames property.
         * 
         * @param value
         *     allowed object is
         *     {@link AdtranCorrelationPolicies.AdtranAgingEvents.CascadeTarget.EventNames }
         *     
         */
        public AdtranCorrelationPolicies.AdtranLPortCorrelation.AdtLPortPPPAlarm getAdtLPortPPPAlarm() {
            return adtLPortPPPAlarm;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "eventNames"
        })
        public static class AdtLPortCorrKeys {

            @XmlElement(required = true)
            protected AdtranCorrelationPolicies.AdtranLPortCorrelation.AdtLPortCorrKeys.EventNames eventNames;

            /**
             * Gets the value of the eventNames property.
             * 
             * @return
             *     possible object is
             *     {@link AdtranCorrelationPolicies.PportProcessing.FileTarget.EventNames }
             *     
             */
            public AdtranCorrelationPolicies.AdtranLPortCorrelation.AdtLPortCorrKeys.EventNames getEventNames() {
                return eventNames;
            }

            /**
             * Sets the value of the eventNames property.
             * 
             * @param value
             *     allowed object is
             *     {@link AdtranCorrelationPolicies.PportProcessing.FileTarget.EventNames }
             *     
             */
            public void setEventNames(AdtranCorrelationPolicies.AdtranLPortCorrelation.AdtLPortCorrKeys.EventNames value) {
                this.eventNames = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "eventName"
            })
            public static class EventNames {

                protected List<String> eventName;

                /**
                 * Gets the value of the eventName property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the eventName property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getEventName().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getEventName() {
                    if (eventName == null) {
                        eventName = new ArrayList<String>();
                    }
                    return this.eventName;
                }

            }

        }
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "eventNames"
        })
        public static class AdtLPortPPPAlarm {

            @XmlElement(required = true)
            protected AdtranCorrelationPolicies.AdtranLPortCorrelation.AdtLPortPPPAlarm.EventNames eventNames;

            /**
             * Gets the value of the eventNames property.
             * 
             * @return
             *     possible object is
             *     {@link AdtranCorrelationPolicies.PportProcessing.FileTarget.EventNames }
             *     
             */
            public AdtranCorrelationPolicies.AdtranLPortCorrelation.AdtLPortPPPAlarm.EventNames getEventNames() {
                return eventNames;
            }

            /**
             * Sets the value of the eventNames property.
             * 
             * @param value
             *     allowed object is
             *     {@link AdtranCorrelationPolicies.PportProcessing.FileTarget.EventNames }
             *     
             */
            public void setEventNames(AdtranCorrelationPolicies.AdtranLPortCorrelation.AdtLPortPPPAlarm.EventNames value) {
                this.eventNames = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "eventName"
            })
            public static class EventNames {

                protected List<String> eventName;

                /**
                 * Gets the value of the eventName property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the eventName property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getEventName().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getEventName() {  
                    if (eventName == null) {
                        eventName = new ArrayList<String>();
                    }
                    return this.eventName;
                }

            }

        }  
    }
    
    
    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="enablePublish" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="eventNames">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "eventNames"
    })
    public static class NtdCorrelation {

        @XmlElement(required = true)
        protected AdtranCorrelationPolicies.NtdCorrelation.EventNames eventNames;

        /**
         * Gets the value of the eventNames property.
         * 
         * @return
         *     possible object is
         *     {@link AdtranCorrelationPolicies.NtdCorrelation.EventNames }
         *     
         */
        public AdtranCorrelationPolicies.NtdCorrelation.EventNames getEventNames() {
            return eventNames;
        }

        /**
         * Sets the value of the eventNames property.
         * 
         * @param value
         *     allowed object is
         *     {@link AdtranCorrelationPolicies.NtdCorrelation.EventNames }
         *     
         */
        public void setEventNames(AdtranCorrelationPolicies.NtdCorrelation.EventNames value) {
            this.eventNames = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "eventName"
        })
        public static class EventNames {

            protected List<String> eventName;

            /**
             * Gets the value of the eventName property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the eventName property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getEventName().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getEventName() {
                if (eventName == null) {
                    eventName = new ArrayList<String>();
                }
                return this.eventName;
            }

        }

    }   
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "eventNames"
    })
    public static class VrfUpdate {

        @XmlElement(required = true)
        protected AdtranCorrelationPolicies.VrfUpdate.EventNames eventNames;

        /**
         * Gets the value of the eventNames property.
         * 
         * @return
         *     possible object is
         *     {@link AdtranCorrelationPolicies.NtdCorrelation.EventNames }
         *     
         */
        public AdtranCorrelationPolicies.VrfUpdate.EventNames getEventNames() {
            return eventNames;
        }

        /**
         * Sets the value of the eventNames property.
         * 
         * @param value
         *     allowed object is
         *     {@link AdtranCorrelationPolicies.NtdCorrelation.EventNames }
         *     
         */
        public void setEventNames(AdtranCorrelationPolicies.VrfUpdate.EventNames value) {
            this.eventNames = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "eventName"
        })
        public static class EventNames {

            protected List<String> eventName;

            /**
             * Gets the value of the eventName property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the eventName property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getEventName().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getEventName() {
                if (eventName == null) {
                    eventName = new ArrayList<String>();
                }
                return this.eventName;
            }

        }

    }   

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "eventNames"
    })
    public static class AdtranCfmAlarm {

        @XmlElement(required = true)
        protected AdtranCorrelationPolicies.AdtranCfmAlarm.EventNames eventNames;

        /**
         * Gets the value of the eventNames property.
         * 
         * @return
         *     possible object is
         *     {@link AdtranCorrelationPolicies.NtdCorrelation.EventNames }
         *     
         */
        public AdtranCorrelationPolicies.AdtranCfmAlarm.EventNames getEventNames() {
            return eventNames;
        }

        /**
         * Sets the value of the eventNames property.
         * 
         * @param value
         *     allowed object is
         *     {@link AdtranCorrelationPolicies.NtdCorrelation.EventNames }
         *     
         */
        public void setEventNames(AdtranCorrelationPolicies.AdtranCfmAlarm.EventNames value) {
            this.eventNames = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "eventName"
        })
        public static class EventNames {

            protected List<String> eventName;

            /**
             * Gets the value of the eventName property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the eventName property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getEventName().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getEventName() {
                if (eventName == null) {
                    eventName = new ArrayList<String>();
                }
                return this.eventName;
            }

        }

    }     
    
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "eventNames"
    })
    public static class EnrichLPortAlarm {

        @XmlElement(required = true)
        protected AdtranCorrelationPolicies.EnrichLPortAlarm.EventNames eventNames;

        /**
         * Gets the value of the eventNames property.
         * 
         * @return
         *     possible object is
         *     {@link AdtranCorrelationPolicies.NtdCorrelation.EventNames }
         *     
         */
        public AdtranCorrelationPolicies.EnrichLPortAlarm.EventNames getEventNames() {
            return eventNames;
        }

        /**
         * Sets the value of the eventNames property.
         * 
         * @param value
         *     allowed object is
         *     {@link AdtranCorrelationPolicies.NtdCorrelation.EventNames }
         *     
         */
        public void setEventNames(AdtranCorrelationPolicies.EnrichLPortAlarm.EventNames value) {
            this.eventNames = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "eventName"
        })
        public static class EventNames {

            protected List<String> eventName;

            /**
             * Gets the value of the eventName property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the eventName property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getEventName().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getEventName() {
                if (eventName == null) {
                    eventName = new ArrayList<String>();
                }
                return this.eventName;
            }

        }

    }   
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "NTEDomain",
        "IPAGDomain"
    })
    public static class  LportDomainClassification{

        protected AdtranCorrelationPolicies.LportDomainClassification.NTEDomain NTEDomain;
        protected AdtranCorrelationPolicies.LportDomainClassification.IPAGDomain IPAGDomain;
        /**
         * Gets the value of the eventNames property.
         * 
         * @return
         *     possible object is
         *     {@link AdtranCorrelationPolicies.AdtranAgingEvents.CascadeTarget.EventNames }
         *     
         */
        public AdtranCorrelationPolicies.LportDomainClassification.NTEDomain getNTEDomainKeys() {
            return NTEDomain;
        }

        /**
         * Sets the value of the eventNames property.
         * 
         * @param value
         *     allowed object is
         *     {@link AdtranCorrelationPolicies.AdtranAgingEvents.CascadeTarget.EventNames }
         *     
         */
        public AdtranCorrelationPolicies.LportDomainClassification.IPAGDomain getIPAGDomainAlarms() {
            return IPAGDomain;   
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "eventNames"
        })
        public static class NTEDomain {

            @XmlElement(required = true)
            protected AdtranCorrelationPolicies.LportDomainClassification.NTEDomain.EventNames eventNames;

            /**
             * Gets the value of the eventNames property.
             * 
             * @return
             *     possible object is
             *     {@link AdtranCorrelationPolicies.PportProcessing.FileTarget.EventNames }
             *     
             */
            public AdtranCorrelationPolicies.LportDomainClassification.NTEDomain.EventNames getEventNames() {
                return eventNames;
            }

            /**
             * Sets the value of the eventNames property.
             * 
             * @param value
             *     allowed object is
             *     {@link AdtranCorrelationPolicies.PportProcessing.FileTarget.EventNames }
             *     
             */
            public void setEventNames(AdtranCorrelationPolicies.LportDomainClassification.NTEDomain.EventNames value) {
                this.eventNames = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "eventName"
            })
            public static class EventNames {

                protected List<String> eventName;

                /**
                 * Gets the value of the eventName property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the eventName property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getEventName().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getEventName() {
                    if (eventName == null) {
                        eventName = new ArrayList<String>();
                    }
                    return this.eventName;
                }

            }

        }
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "eventNames"
        })
        public static class IPAGDomain {

            @XmlElement(required = true)
            protected AdtranCorrelationPolicies.LportDomainClassification.IPAGDomain.EventNames eventNames;

            /**
             * Gets the value of the eventNames property.
             * 
             * @return
             *     possible object is
             *     {@link AdtranCorrelationPolicies.PportProcessing.FileTarget.EventNames }
             *     
             */
            public AdtranCorrelationPolicies.LportDomainClassification.IPAGDomain.EventNames getEventNames() {
                return eventNames;
            }

            /**
             * Sets the value of the eventNames property.
             * 
             * @param value
             *     allowed object is
             *     {@link AdtranCorrelationPolicies.PportProcessing.FileTarget.EventNames }
             *     
             */
            public void setEventNames(AdtranCorrelationPolicies.LportDomainClassification.IPAGDomain.EventNames value) {
                this.eventNames = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "eventName"
            })
            public static class EventNames {

                protected List<String> eventName;

                /**
                 * Gets the value of the eventName property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list, 
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the eventName property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getEventName().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getEventName() {  
                    if (eventName == null) {
                        eventName = new ArrayList<String>();
                    }
                    return this.eventName;
                }

            }

        }
    }

}
