//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.10 at 07:53:45 PM CDT 
//

package com.att.gfp.data.config;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.att.gfp.data.config.IpagPolicies.CpeCdcAlarms.CpeCdcAlarm;

/**
 * Parses the IPAG config xml file
 * 
 * @author st133d
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "HealthTraps", "SuperEmuxDevices","CdcAlarms","CpeCdcAlarms","Suppressions" })
@XmlRootElement(name = "IpagPolicies")
public class IpagPolicies {

	@XmlElement(required = true)
	protected IpagPolicies.HealthTraps HealthTraps;
	@XmlElement(required = true)
	protected IpagPolicies.SuperEmuxDevices SuperEmuxDevices;
	@XmlElement(required = true)
	protected IpagPolicies.CdcAlarms CdcAlarms;
	@XmlElement(required = true)
	protected IpagPolicies.CpeCdcAlarms CpeCdcAlarms;
	protected IpagPolicies.Suppressions Suppressions;
	 
	public IpagPolicies.Suppressions getSuppressions() {
		return Suppressions;
	}

	public void setSuppressions(IpagPolicies.Suppressions suppressions) {
		Suppressions = suppressions;
	}
 
	public IpagPolicies.CpeCdcAlarms getCpeCdcAlarms() {
		return CpeCdcAlarms;
	}
 
	public void setCpeCdcAlarms(IpagPolicies.CpeCdcAlarms cpeCdcAlarms) {
		CpeCdcAlarms = cpeCdcAlarms;
	}

	public IpagPolicies.CdcAlarms getCdcAlarms() {
		return CdcAlarms;
	}

	public void setCdcAlarms(IpagPolicies.CdcAlarms cdcAlarms) {
		CdcAlarms = cdcAlarms;
	}

	public IpagPolicies.SuperEmuxDevices getSuperEmuxDevices() { 
		return SuperEmuxDevices;
	}

	public void setSuperEmuxDevices(IpagPolicies.SuperEmuxDevices superEmuxDevices) {
		SuperEmuxDevices = superEmuxDevices;
	}
  
	public IpagPolicies.HealthTraps getHealthTraps() {
		return HealthTraps;
	}

	public void setHealthTraps(IpagPolicies.HealthTraps healthTraps) {
		this.HealthTraps = healthTraps;
	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "eventNames" })
	public static class HealthTraps {

		protected IpagPolicies.HealthTraps.EventNames eventNames;

		/**
		 * Gets the value of the eventNames property.
		 * 
		 * @return possible object is
		 *         {@link CascadePolicies.CascadeTargets.CascadeTarget.EventNames }
		 * 
		 */
		public IpagPolicies.HealthTraps.EventNames getEventNames() {
			return eventNames;
		}

		/**
		 * Sets the value of the eventNames property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link CascadePolicies.CascadeTargets.CascadeTarget.EventNames }
		 * 
		 */
		public void setEventNames(IpagPolicies.HealthTraps.EventNames value) {
			this.eventNames = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "eventName" })
		public static class EventNames {

			protected List<String> eventName;

			/**
			 * Gets the value of the eventName property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the eventName property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getEventName().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link String }
			 * 
			 * 
			 */
			public List<String> getEventName() {
				if (eventName == null) {
					eventName = new ArrayList<String>();
				}
				return this.eventName;
			}

		}

	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "eventNames" })
	public static class CdcAlarms {

		protected IpagPolicies.CdcAlarms.EventNames eventNames;

		/**
		 * Gets the value of the eventNames property.
		 * 
		 * @return possible object is
		 *         {@link CascadePolicies.CascadeTargets.CascadeTarget.EventNames }
		 * 
		 */
		public IpagPolicies.CdcAlarms.EventNames getEventNames() {
			return eventNames;
		}

		/**
		 * Sets the value of the eventNames property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link CascadePolicies.CascadeTargets.CascadeTarget.EventNames }
		 * 
		 */
		public void setEventNames(IpagPolicies.CdcAlarms.EventNames value) {
			this.eventNames = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "eventName" })
		public static class EventNames {

			protected List<String> eventName;

			/**
			 * Gets the value of the eventName property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the eventName property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getEventName().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link String }
			 * 
			 * 
			 */
			public List<String> getEventName() {
				if (eventName == null) {
					eventName = new ArrayList<String>();
				}
				return this.eventName;
			}

		}

	}
	
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "SuperEmux" })
	public static class SuperEmuxDevices {

        @XmlElement(required = true)
		protected List<IpagPolicies.SuperEmuxDevices.SuperEmux> SuperEmux;


		public List<IpagPolicies.SuperEmuxDevices.SuperEmux> getSuperEmux() {
			if(SuperEmux == null) {
				SuperEmux = new ArrayList<IpagPolicies.SuperEmuxDevices.SuperEmux>();   
			} 
			return SuperEmux;
		}


		public void setSuperEmux(List<IpagPolicies.SuperEmuxDevices.SuperEmux> superEmux) {
			SuperEmux = superEmux;
		}


		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "deviceModel", "portAidMapping" })
		public static class SuperEmux {

	        @XmlElement(required = true)
			protected String deviceModel;
	        @XmlElement(required = true)
			protected List<IpagPolicies.SuperEmuxDevices.SuperEmux.portAidMapping> portAidMapping;

			public List<IpagPolicies.SuperEmuxDevices.SuperEmux.portAidMapping> getPortAidMapping() {
				if(portAidMapping == null) {
					portAidMapping = new ArrayList<IpagPolicies.SuperEmuxDevices.SuperEmux.portAidMapping>(); 
				}
				return portAidMapping;  
			}

			public void setPortAidMapping(
					List<IpagPolicies.SuperEmuxDevices.SuperEmux.portAidMapping> portAidMapping) {
				this.portAidMapping = portAidMapping;
			}

			public String getDeviceModel() {    
				return deviceModel;
			}

			public void setDeviceModel(String deviceModel) {
				this.deviceModel = deviceModel;
			}


			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "portAid", "gcpPortAid" })
			public static class portAidMapping {

		        @XmlElement(required = true)
				protected String portAid;
		        @XmlElement(required = true)
				protected String gcpPortAid;

				public String getPortAid() {
					return portAid;
				}  

				public void setPortAid(String portAid) {
					this.portAid = portAid; 
				}  

				public String getGcpPortAid() {
					return gcpPortAid;
				}  

				public void setGcpPortAid(String gcpPortAid) {
					this.gcpPortAid = gcpPortAid;
				}
			}

		}
	}
	
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "eventNames","CpeCdcAlarm" })
	public static class CpeCdcAlarms {

		protected IpagPolicies.CpeCdcAlarms.EventNames eventNames;
		
		public IpagPolicies.CpeCdcAlarms.EventNames getEventNames() {
			return eventNames;
		}


		public void setEventNames(IpagPolicies.CpeCdcAlarms.EventNames eventNames) {
			this.eventNames = eventNames;
		}

		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "eventName" })
		public static class EventNames {

			protected List<String> eventName; 

			/**
			 * Gets the value of the eventName property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the eventName property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getEventName().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link String }
			 * 
			 * 
			 */
			public List<String> getEventName() {
				if (eventName == null) {
					eventName = new ArrayList<String>();
				}
				return this.eventName;
			}

		}
		
        @XmlElement(required = true)
		protected List<IpagPolicies.CpeCdcAlarms.CpeCdcAlarm> CpeCdcAlarm;

 
		public List<IpagPolicies.CpeCdcAlarms.CpeCdcAlarm> getCpeCdcAlarm() {
			if(CpeCdcAlarm == null) {
				CpeCdcAlarm = new ArrayList<IpagPolicies.CpeCdcAlarms.CpeCdcAlarm>();   
			}
			return CpeCdcAlarm;
		}


		public void setCpeCdcAlarm(List<IpagPolicies.CpeCdcAlarms.CpeCdcAlarm> cpeCdcAlarm) {
			CpeCdcAlarm = cpeCdcAlarm;
		} 
		
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "eventName", "processingType" })
		public static class CpeCdcAlarm {

	        @XmlElement(required = true)
			protected String eventName;
	        @XmlElement(required = true)
			protected String processingType;
			public String getEventName() {
				return eventName;
			}
			public void setEventName(String eventName) {
				this.eventName = eventName;
			}
			public String getProcessingType() { 
				return processingType;
			}
			public void setProcessingType(String processingType) {
				this.processingType = processingType;
			}

		}
	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "Suppression" })
	public static class Suppressions {

		protected List<IpagPolicies.Suppressions.Suppression> Suppression;
		

		public List<IpagPolicies.Suppressions.Suppression> getSuppression() {
			return Suppression;
		}


		public void setSuppression(
				List<IpagPolicies.Suppressions.Suppression> suppression) {
			Suppression = suppression;
		}

		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "key","value" })
		public static class Suppression { 

			protected String key;  
			public String getKey() {
				return key;
			}
			public void setKey(String key) {
				this.key = key;
			}
			public String getValue() {
				return value;
			}
			public void setValue(String value) {
				this.value = value;
			}
			protected String value;  

	}
	}
	
}
