//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.10 at 07:53:45 PM CDT 
//

package com.att.gfp.data.config;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Parses the IPAG config xml file
 * 
 * @author st133d
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "UCAInstance" })
@XmlRootElement(name = "UCAInstnaces")
public class UCAInstnaces {

	@XmlElement(required = true)
	protected List<UCAInstnaces.UCAInstance> UCAInstance;
	
	
	public List<UCAInstnaces.UCAInstance> getUCAInstance() {
		return UCAInstance;
	}


	public void setUCAInstance(List<UCAInstnaces.UCAInstance> uCAInstance) {
		UCAInstance = uCAInstance;
	} 


	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "Instancename","VpNames" }) 
	public static class UCAInstance {

		protected String Instancename;
		protected UCAInstnaces.UCAInstance.VpNames VpNames;
		
		public String getInstancename() {
			return Instancename;
		}

		public void setInstancename(String instancename) {
			Instancename = instancename;
		}
		public UCAInstnaces.UCAInstance.VpNames getVpNames() {
			return VpNames;
		}


		public void setVpNames(UCAInstnaces.UCAInstance.VpNames VpNames) {
			this.VpNames = VpNames;
		}

		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "VpName" })
		public static class VpNames {
			 
 
			public void setVpName(List<String> vpName) {
				VpName = vpName;
			}


			protected List<String> VpName; 

			/**
			 * Gets the value of the eventName property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the eventName property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getEventName().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link String }
			 * 
			 * 
			 */
			public List<String> getVpName() {
				if (VpName == null) {
					VpName = new ArrayList<String>();
				}
				return this.VpName; 
			}

		}
		
	}

}
