//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.10 at 07:53:45 PM CDT 
//


package com.att.gfp.data.preprocess.conf;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.att.gfp.data.preprocess.conf package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.att.gfp.data.preprocess.conf
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PreProcessPolicies }
     * 
     */
    public PreProcessPolicies createPreProcessPolicies() {
        return new PreProcessPolicies();
    }

    /**
     * Create an instance of {@link PreProcessPolicies.CascadeTargets }
     * 
     */
    public PreProcessPolicies.CascadeTargets createPreProcessPoliciesCascadeTargets() {
        return new PreProcessPolicies.CascadeTargets();
    }

    /**
     * Create an instance of {@link PreProcessPolicies.CascadeTargets.CascadeTarget }
     * 
     */
    public PreProcessPolicies.CascadeTargets.CascadeTarget createPreProcessPoliciesCascadeTargetsCascadeTarget() {
        return new PreProcessPolicies.CascadeTargets.CascadeTarget();
    }

    /**
     * Create an instance of {@link PreProcessPolicies.FileTargets }
     * 
     */
    public PreProcessPolicies.FileTargets createPreProcessPoliciesFileTargets() {
        return new PreProcessPolicies.FileTargets();
    }

    /**
     * Create an instance of {@link PreProcessPolicies.FileTargets.FileTarget }
     * 
     */
    public PreProcessPolicies.FileTargets.FileTarget createPreProcessPoliciesFileTargetsFileTarget() {
        return new PreProcessPolicies.FileTargets.FileTarget();
    }

    /**
     * Create an instance of {@link PreProcessPolicies.PassThru }
     * 
     */
    public PreProcessPolicies.PassThru createPreProcessPoliciesPassThru() {
        return new PreProcessPolicies.PassThru();
    }

    /**
     * Create an instance of {@link PreProcessPolicies.CascadeTargets.CascadeTarget.EventNames }
     * 
     */
    public PreProcessPolicies.CascadeTargets.CascadeTarget.EventNames createPreProcessPoliciesCascadeTargetsCascadeTargetEventNames() {
        return new PreProcessPolicies.CascadeTargets.CascadeTarget.EventNames();
    }

    /**
     * Create an instance of {@link PreProcessPolicies.FileTargets.FileTarget.EventNames }
     * 
     */
    public PreProcessPolicies.FileTargets.FileTarget.EventNames createPreProcessPoliciesFileTargetsFileTargetEventNames() {
        return new PreProcessPolicies.FileTargets.FileTarget.EventNames();
    }

    /**
     * Create an instance of {@link PreProcessPolicies.PassThru.EventNames }
     * 
     */
    public PreProcessPolicies.PassThru.EventNames createPreProcessPoliciesPassThruEventNames() {
        return new PreProcessPolicies.PassThru.EventNames();
    }

}
